{% set version = '3.1.50' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-randomfields
  version: {{ version|replace("-", "_") }}

source:
  fn: RandomFields_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/RandomFields_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/RandomFields/RandomFields_{{ version }}.tar.gz
  sha256: 2d6a07c3a716ce20f9c685deb59e8fcc64fd52c8a50b0f04baf451b6b928e848

build:
  merge_build_host: True  # [win]
  number: 1
  script: R CMD INSTALL --build .
  skip: True  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - r-base
    - r-randomfieldsutils
    - r-sp
  run:
    - r-base
    - r-randomfieldsutils
    - r-sp

test:
  commands:
    - $R -e "library('RandomFields')"  # [not win]
    - "\"%R%\" -e \"library('RandomFields')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/RandomFields
  license: GPL (>= 3)
  summary: Methods for the inference on and the simulation of Gaussian fields are provided, as
    well as methods for the simulation of extreme value random fields.

extra:
  recipe-maintainers:
    - ocefpaf
