appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: B4zlh9jScS9RdRWL1gMDJ/qBui6xlM4OVKKOMS4v7NyZrTO2/+70syxFMYkx2OxMhXgkIs0V4NiKWxxCeTUWOgn2+/NZHWAA58mbVfyvSsedlPAqr58kLUomB34hPdr81z/otGI/0/RPBotTOz2lYypZ3ptlFwo2nzRgJmHT+3I++FDMWz2DTw9W5Y5Ba0p0XlUP0g7HQ/zHoiPmYfDDruPsd814qoRnuXBkjoH+E2c1vIlJhSZbFbdiwEoWYhL9CZmzzbAH2XOKeTvGfPaR8pIKZdlvFhliyXYCMZr5upAeki7m3WSORndA7gDXsvKio1If8BD3oRlis3a8Y2sZUGtD6bM1sk+2wzRYye+DBMbdxU2mqnmbdLbW9uYDsFGKLDpJkzfkhosdt4CEXQ9EAEw2aqBjxO7TQR76tpujMgiBHVxtiSawYS4iXhVzyTlD8PCKxllddPbu5blE59OZJe7lqfUzEiOz58egzICtfxKdolm6LrrlpCTLTjpIo/zPBIY86jJyJdI9ExoXthIu7t2Z+MX+1tgDwXb6iniku53WThqNVg5QhWM2UeKewSpvx5bLynKolckhZOpNQ2G5Fydqm2It2Pgk2f8VKZvy7FJXa0ijJspw+BpsOhHpDRTMByyoId8oFFOGVMyhwKPPzkjZteIvuOcd2J7LEvtKjJI=}
