travis:
  secure:
    BINSTAR_TOKEN: 4MP4lYF0DLO/xDJJL8gr83mly04DrrO6eG5qqWWe8SCyfqfJFcyWzrS8hErLETKUiBX8s3svI4F6NaH1AF+Lr7ZY5xx+CxwGMHIfjiWkY02xR+r3sjv5YsFGZGJgLsbU4hQG86uI2Ik1bu5YszIRwgv18tO3KyVVHHIn+JmQ8abbmKbBUtNh5LS3B1k1XI4GqlKtN0RoWYjJsxwFIM4JKE/xYATGup3sqt9pTEDt0I0Q6k12Aeot4JGO39kr7JZRtLrlEAst3Tzu3LGZni2VYl2moe9OzSCqp+PF406gMmgxfyw/bkM1m9SiAO2k+m6vgvWShmFHFKDDjhzj2uBdKYo9+QixmfcwR+7jNeGlyrCoebl/DyredCMigRLxFA+8VeXjz0oazCjW9tdU6CkWmbvePA+NoiZPXYOMiVj7dRPVMWcGtHR35PVB394X/i76IxLYvz67/Je8u1A/DpSZKhbG+T7/5ShSbsfa0LLQeUJ/uiG9NpAQMJgh6qQgcBBoI8Mr4pYEXDS4kaD+DFfYHr5Di22Cnj+yi9yCksALoUEndRVNkjT0UzM7TtaOQEmGv70nJB09gXtikwzkMZO9Yyqlkm2am9Ph9HzKF3lZVnOJn2ihesKLIImKYxA3sQelw0e9w7KD43KCwYoIyzRM5nkmbochoqScU4UemiXKse4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
